services:
  - type: web
    name: whop-clipper-backend
    env: python
    pythonVersion: "3.11.0"
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r Backend/requirements.txt
      pip uninstall moviepy
      pip install moviepy==1.0.3
      pip install imageio==2.31.1
      pip install imageio-ffmpeg==0.4.9
    startCommand: gunicorn Backend.app:app
    rootDir: .
    envVars:
      - key: PORT
        value: 10000
      - key: UPLOAD_FOLDER
        value: uploads
      - key: PROCESSED_FOLDER
        value: processed 