services:
  - type: web
    name: whop-clipper-backend
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r Backend/requirements.txt
    startCommand: gunicorn Backend.app:app
    rootDir: /opt/render/project/src
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000 