services:
  - type: web
    name: whop-clipper-backend
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r Backend/requirements.txt
      pip uninstall moviepy -y
      pip install moviepy==1.0.3
    startCommand: gunicorn Backend.app:app
    rootDir: /opt/render/project/src
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: UPLOAD_FOLDER
        value: uploads
      - key: PROCESSED_FOLDER
        value: processed 