services:
  - type: web
    name: whop-clipper-backend
    env: python
    pythonVersion: "3.11.0"
    buildCommand: |
      python3 -m pip install --upgrade pip
      pip3 install --upgrade pip
      pip3 install -r Backend/requirements.txt
      pip3 uninstall moviepy -y
      pip3 install moviepy==1.0.3
      pip3 install imageio==2.31.1
      pip3 install imageio-ffmpeg==0.4.9
    startCommand: cd /opt/render/project/src && gunicorn Backend.app:app
    rootDir: /opt/render/project/src
    envVars:
      - key: PORT
        value: 10000
      - key: UPLOAD_FOLDER
        value: uploads
      - key: PROCESSED_FOLDER
        value: processed 