services:
  - type: web
    name: whop-clipper-backend
    env: python
    pythonVersion: "3.11.0"
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn Backend.app:app
    rootDir: .
    envVars:
      - key: PORT
        value: 10000
      - key: UPLOAD_FOLDER
        value: uploads
      - key: PROCESSED_FOLDER
        value: processed 